(() => {
  const SETTINGS_BOOKING_NO = 'BW-ADMIN-CONFIG';
  const DEFAULTS = { A: [6], B: [2, 4, 5] };
  const DOW = ['일','월','화','수','목','금','토'];
  let allBookings = [];
  let configRecord = null;
  const $ = (s) => document.querySelector(s);
  function escapeHtml(value){return String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
  function renderDow(containerId,course,selected){const box=document.getElementById(containerId);box.innerHTML=DOW.map((label,idx)=>`<label class="dow-pill"><input type="checkbox" data-course="${course}" value="${idx}" ${selected.includes(idx)?'checked':''}><span>${label}</span></label>`).join('')}
  function parseSettings(record){if(!record||!record.petName)return{A:[...DEFAULTS.A],B:[...DEFAULTS.B]};try{const parsed=JSON.parse(record.petName);return{A:Array.isArray(parsed.A)?parsed.A.map(Number).filter(n=>n>=0&&n<=6):[...DEFAULTS.A],B:Array.isArray(parsed.B)?parsed.B.map(Number).filter(n=>n>=0&&n<=6):[...DEFAULTS.B]}}catch{return{A:[...DEFAULTS.A],B:[...DEFAULTS.B]}}}
  function checkedValues(course){return Array.from(document.querySelectorAll(`input[data-course="${course}"]:checked`)).map(el=>Number(el.value)).sort((a,b)=>a-b)}
  async function loadAll(){$('#saveMsg').textContent='데이터를 불러오는 중...';allBookings=await BW.listBookings();configRecord=allBookings.find(b=>b.bookingNo===SETTINGS_BOOKING_NO&&b.course==='CONFIG')||null;const settings=parseSettings(configRecord);renderDow('dowA','A',settings.A);renderDow('dowB','B',settings.B);$('#saveMsg').textContent='';renderBookings()}
  async function saveSchedule(){const btn=$('#saveScheduleBtn');const settings={A:checkedValues('A'),B:checkedValues('B')};if(settings.A.length===0&&!confirm('코스 A의 예약 가능 요일이 하나도 없습니다. 그대로 저장할까요?'))return;if(settings.B.length===0&&!confirm('코스 B의 예약 가능 요일이 하나도 없습니다. 그대로 저장할까요?'))return;btn.disabled=true;$('#saveMsg').textContent='저장 중...';const payload={bookingNo:SETTINGS_BOOKING_NO,course:'CONFIG',date:'2099-12-31',people:0,name:'운영요일 설정',phone:'-',email:'-',consent:true,status:'설정',petName:JSON.stringify(settings),petBreed:'',petSize:'',petVaccinated:false,petSociality:''};try{if(configRecord&&configRecord.id){const updated=await BW.patchBooking(configRecord.id,payload);configRecord={...configRecord,...payload,...(updated||{})}}else{configRecord=await BW.createBooking(payload)}$('#saveMsg').textContent='✓ 저장되었습니다. 고객 예약 달력에 반영됩니다.';await loadAll()}catch(err){console.error(err);$('#saveMsg').textContent='저장에 실패했습니다. 콘솔 오류를 확인해 주세요.';alert('운영요일 저장 중 오류가 발생했습니다.')}finally{btn.disabled=false}}
  function publicBookings(){return allBookings.filter(b=>b.course==='A'||b.course==='B').sort((a,b)=>{const d=String(b.date||'').localeCompare(String(a.date||''));return d!==0?d:String(b.bookingNo||'').localeCompare(String(a.bookingNo||''))})}
  function renderBookings(){const bookings=publicBookings();$('#countAll').textContent=bookings.length;$('#countConfirmed').textContent=bookings.filter(b=>b.status!=='취소').length;$('#countA').textContent=bookings.filter(b=>b.course==='A').length;$('#countB').textContent=bookings.filter(b=>b.course==='B').length;const course=$('#courseFilter').value,status=$('#statusFilter').value,q=$('#searchInput').value.trim().toLowerCase();const filtered=bookings.filter(b=>{if(course&&b.course!==course)return false;if(status&&b.status!==status)return false;if(q){const hay=[b.bookingNo,b.name,b.phone,b.email,b.date,b.petName,b.nationality].join(' ').toLowerCase();if(!hay.includes(q))return false}return true});const tbody=$('#bookingRows');if(!filtered.length){tbody.innerHTML='<tr><td colspan="9" class="empty-state">조건에 맞는 예약이 없습니다.</td></tr>';return}tbody.innerHTML=filtered.map(b=>{const extra=b.course==='A'?(b.petName||'-'):(b.nationality||'-'),cancelled=b.status==='취소';return `<tr><td><strong>${escapeHtml(b.bookingNo||'-')}</strong></td><td>${escapeHtml(b.date||'-')}</td><td><span class="course-badge">코스 ${escapeHtml(b.course)}</span></td><td>${escapeHtml(b.people??'-')}</td><td>${escapeHtml(b.name||'-')}</td><td>${escapeHtml(b.phone||'-')}</td><td>${escapeHtml(b.email||'-')}</td><td>${escapeHtml(extra)}</td><td><span class="status ${cancelled?'cancelled':'confirmed'}">${escapeHtml(b.status||'확정')}</span></td></tr>`}).join('')}
  document.addEventListener('DOMContentLoaded',async()=>{$('#saveScheduleBtn').addEventListener('click',saveSchedule);$('#reloadScheduleBtn').addEventListener('click',loadAll);$('#refreshBtn').addEventListener('click',loadAll);$('#courseFilter').addEventListener('change',renderBookings);$('#statusFilter').addEventListener('change',renderBookings);$('#searchInput').addEventListener('input',renderBookings);try{await loadAll()}catch(err){console.error(err);$('#saveMsg').textContent='데이터 연결 실패';$('#bookingRows').innerHTML='<tr><td colspan="9" class="empty-state">예약 데이터를 불러오지 못했습니다. Vercel 배포 주소에서 다시 확인해 주세요.</td></tr>'}})
})();